baseURL = "https://blog.vidsey.io/"
languageCode = "en-us"
title = "Vidsey Blog"
theme = "bleak"

[params]
Subtitle = "Procedural video generation"
description = "Procedural video generation"
cover = "/images/cover.jpg"
logo = "/images/logo.svg"

 # Google analytics
  googleAnalyticsUserID = "UA-99135840-1"

[params.author]
image = "/content/images/logo200.jpg"
website = "https://blog.vidsey.io"