baseURL = "https://blog.vidsey.io/"
languageCode = "en-us"
title = "Vidsey Blog"
theme = "bleak"

[params]
Subtitle = "Procedural video generation"
description = "Procedural video generation"
cover = "/images/cover.jpg"
logo = "/images/logo.svg"
googleAnalyticsUserID = "UA-99135840-1"
codeLocation = "_examples"

[blackfriday]
hrefTargetBlank = true

[params.author]
image = "/content/images/logo200.jpg"
website = "https://blog.vidsey.io"

[params.staff.alex]
name = "Alex Guerrieri"
twitter = "KlaidLiadon"

[params.staff.rok]
name = "Rok Biderman"
twitter = "RokBiderman"

[params.staff.vesna]
name = "Vesna Planko"
twitter = "VesnaPlanko"
